name: gpth
description: 'Tool to help you with exporting stuff from Google Photos'
version: 3.4.4
homepage: 'https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper'
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  mime: ^2.0.0
  collection: ^1.18.0
  convert: ^3.1.1
  fuzzysearch: ^0.1.3
  crypto: ^3.0.3
  exif: ^3.3.0
  console_bars: ^1.2.0
  file_picker_desktop:
    path: ./file_picker_desktop/
  #  archive:
  #    git:
  #      url: https://github.com/TheLastGimbus/archive.git
  #      ref: fix-windoza-extract-errors
  proper_filesize: ^1.0.2
  unorm_dart: ^0.3.0
  win32: ^5.5.1
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.6
