# This is quick action to build exe and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build nightly

on:
  workflow_dispatch:
  push:
    branches:
      - prerelease

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dart-lang/setup-dart@v1.7.1
      - run: dart pub get
      - name: Get version
        id: version
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
          VERSION=$(powershell -Command "(Get-Content pubspec.yaml | Select-String '^version:').ToString().Split(':')[1].Trim()")
          else
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | cut -d' ' -f2)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build exe
        run: |
          version=${{ steps.version.outputs.version }}
          osname=${{ matrix.os }}
          if [ "$osname" = "ubuntu-latest" ]; then
            osname=linux
          elif [ "$osname" = "macos-latest" ]; then
            osname=macos
          elif [ "$osname" = "windows-latest" ]; then
            osname=windows
          fi
          archname=${{ matrix.arch }}
          outname=gpth-v$version-nightly-$osname-$archname
          if [ "$osname" = "windows" ]; then
            outname="$outname.exe"
          fi
          dart compile exe bin/gpth.dart -o ./$outname
      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: gpth-v${{ steps.version.outputs.version }}-nightly-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'macos-latest' && 'macos' || matrix.os == 'windows-latest' && 'windows' }}-${{ matrix.arch }}
          path: |
            ./gpth-v${{ steps.version.outputs.version }}-nightly-linux-${{ matrix.arch }}
            ./gpth-v${{ steps.version.outputs.version }}-nightly-linux-${{ matrix.arch }}.exe
            ./gpth-v${{ steps.version.outputs.version }}-nightly-macos-${{ matrix.arch }}
            ./gpth-v${{ steps.version.outputs.version }}-nightly-macos-${{ matrix.arch }}.exe
            ./gpth-v${{ steps.version.outputs.version }}-nightly-windows-${{ matrix.arch }}
            ./gpth-v${{ steps.version.outputs.version }}-nightly-windows-${{ matrix.arch }}.exe
          if-no-files-found: error
