# This is quick action to build exe and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build nightly

on:
  workflow_dispatch:
  push:
    branches:
      - prerelease

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm, windows-11-arm, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dart-lang/setup-dart@v1.7.1
      - run: dart pub get
      - name: Get version
        id: version
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
          VERSION=$(powershell -Command "(Get-Content pubspec.yaml | Select-String '^version:').ToString().Split(':')[1].Trim()")
          else
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | cut -d' ' -f2)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build exe
        shell: bash
        run: |
          version=${{ steps.version.outputs.version }}
          osname=${{ matrix.os }}
          arch=${{ contains(matrix.os, 'arm') && 'arm64' || 'x86_64' }}
          # Normalize osname for output file
          if [[ "$osname" == "ubuntu-latest" || "$osname" == "ubuntu-24.04-arm" ]]; then
            osname=linux
          elif [[ "$osname" == "macos-latest" || "$osname" == "macos-13" ]]; then
            osname=macos
          elif [[ "$osname" == "windows-latest" || "$osname" == "windows-11-arm" ]]; then
            osname=windows
          fi
          outname=gpth-v$version-nightly-$osname-$arch
          if [[ "$osname" == "windows" ]]; then
            outname="$outname.exe"
          fi
          dart compile exe bin/gpth.dart -o ./$outname
      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: gpth-v${{ steps.version.outputs.version }}-nightly-${{ contains(matrix.os, 'ubuntu') && 'linux' || contains(matrix.os, 'macos') && 'macos' || contains(matrix.os, 'windows') && 'windows' }}-${{ contains(matrix.os, 'arm') && 'arm64' || 'x86_64' }}
          path: ./gpth-v${{ steps.version.outputs.version }}-nightly-${{ contains(matrix.os, 'ubuntu') && 'linux' || contains(matrix.os, 'macos') && 'macos' || contains(matrix.os, 'windows') && 'windows' }}-${{ contains(matrix.os, 'arm') && 'arm64' || 'x86_64' }}${{ contains(matrix.os, 'windows') && '.exe' || '' }}
          if-no-files-found: error
