# This is quick action to build exe and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build nightly

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dart-lang/setup-dart@v1.7.1
      - run: dart pub get
      - name: Build exe
        run: |
          outname=gpth-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            outname="$outname.exe"
          fi
          dart compile exe bin/gpth.dart -o ./$outname
      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: gpth-nightly-${{ matrix.os }}-${{ matrix.arch }}
          path: ./gpth-${{ matrix.os }}-${{ matrix.arch }}*
          if-no-files-found: error
